%% DEMO_PRETRAINING
%
% Training MDNet models.
%
% Hyeonseob Nam, 2015
%

clear;

%{
mdnet_pretrain('seqsList',...
    {struct('dataset','vot2013','list','pretraining/seqList/vot13-otb.txt'),...
    struct('dataset','vot2014','list','pretraining/seqList/vot14-otb.txt'),...
    struct('dataset','vot2015','list','pretraining/seqList/vot15-otb.txt')},...
    'outFile', fullfile('/home/lrr/workspace/MyMDNet-master/models','mymdnet_myotb.mat'),...
    'roiDir', fullfile('/home/lrr/workspace/MyMDNet-master/models','data_myotb'));
%}

mdnet_pretrain('seqsList',...
    {struct('dataset','otb','list','pretraining/seqList/mymdnet_1new.txt')},...
    'outFile', fullfile('/home/lrr/workspace/MyMDNet-master/models','mymdnet_1new.mat'),...
    'roiDir', fullfile('/home/lrr/workspace/MyMDNet-master/models','data_1new'));
  